#!/bin/bash
cd "$(dirname "$0")"

rm -rf build
mkdir build

tree > build/index.html

#build packages and more to output
echo "[Info] building packages"
./source/build-all

echo "[Info] building repo"
./repo/builder