#!/bin/bash
#pass full private key in "" to as first argument

cd "$(dirname "$0")"

root=$(pwd)

cd build/repo/dists/stable

# Get the private key from the first argument

echo "$1" > key.private

gpg --no-default-keyring --keyring ./temp-keyring.gpg --import key.private

echo "[Info] signing Release"
gpg --no-default-keyring --keyring ./temp-keyring.gpg -abs --output Release.gpg --sign Release

echo "[Info] signing InRelease"
gpg --no-default-keyring --keyring ./temp-keyring.gpg --clearsign -abs --output InRelease --sign Release

echo "[Info] generating public key velvet_repo.asc"
gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --armor > ${root}/build/repo/velvet_repo.asc

#cleanning up
echo "[Info] cleanning up"
rm key.private
rm *.gpg*