#!/bin/bash
#pass full private key in "" to as first argument

cd "$(dirname "$0")"

root=$(pwd)

cd build/repo/dists/stable

# Get the private key from the first argument

echo "$1" > key.private

gpg --no-default-keyring --keyring ./temp-keyring.gpg --import key.private

gpg --no-default-keyring --keyring ./temp-keyring.gpg -abs --output Release.pgp --sign Release

gpg --no-default-keyring --keyring ./temp-keyring.gpg --clearsign -abs --output InRelease --sign Release

gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --armor > ${root}/build/velvet_repo.asc

#cleanning up
rm key.private
rm *.gpg*