#!/bin/bash
#run inside scirpt dir
cd "$(dirname "$0")"
export main=$(pwd)

#build all packages
for buildme in ./packages/*/buildme; do

    chmod +x "./${buildme}"
    "./${buildme}" "$(pwd)/"

done

mkdir ../output -p

for debfile in ./*.deb; do
    mv ${debfile} ../output/$(basename $debfile) -v
done;