#!/bin/bash
#run inside scirpt dir
cd "$(dirname "$0")"

rm -rf ../output #clean up previous build

mkdir ../output

#build all packages
for buildme in ./packages/*/buildme; do
    echo "[Info] running ${buildme}"
    chmod +x "./${buildme}"
    "./${buildme}" "$(pwd)/../output"
    if [ "$?" != "0" ];then
        echo "[error] failed to build ${buildme}" 
        exit 1
    fi

done



